### ISSUE TITLE
[버그, 개선] MFA 라우트 통신 처리

### ISSUE THREAD

**Issue by minsoo-web** [hamsurang/origin#28]
첫 번째는, iframe 에서 route 가 변경되었을 때 iframe 을 부르는 부모랑 싱크하도록 처리한 작업이 있어요 (이건 잘 됨)

근데 부모에서 searchParam 이 바뀌었을 때 iframe 자식이 바뀌어야 해가지고 골치입니다

재현하는 방법:
1. hamsurang.com 으로 진입
  부모 (hamsurang.com/home)
  자식 (home.hamsurang.com)

2. iframe 에서 아무 people 을 눌러본다
  부모 (hamsurang.com/home/people?username=minsour)
  자식 (home.hamsurang.com/people?username=minsour)

3. 부모에서 홈을 눌러본다.
  부모 (hamsurang.com/home)
  자식 (home.hamsurang.com/people?username=minsour)

  기대하는 자식 -> home.hamsurang.com

두 번째 이슈는

지금 app/home 의 layout 에서 모든 페이지의 라우트 변화를 listen 하기 위해서 최상단의 layout 에 useEffect 를 전달했어요

1. 이렇게 되면 layout 이 use client 라서 SSR 이 안 될 것 같다.
2. useSearchParam 을 쓰려면 Suspense 로 감싸라고 next 가 권장한다. 이를 무시하고 빌드성공하려고 

```js
experimental: {
    // ... 
    missingSuspenseWithCSRBailout: false,
  },
```

을 추가했다. 정상은 아닌 것 같아서 고치고 싶다

요구사항
1. 자식 요소의 라우트가 변경될 때 부모의 라우트도 변경시켜야 한다. (새로고침해도 똑같이 그 페이지를 방문할 수 있도록)

지금 제가 작성한 방법을 뜯어 고치셔도 됩니다. ( history.replaceState 방식 )

2. (안 해도 됨) SSR 을 대응하고 싶다

**Comment by minsoo-web** [comment]
두 개처럼 보이지만, 사실 하나의 이슈 같고
제가 작업한 내용과 싱크하도록 수림님이 한 번 작업해보면 좋을 것 같아서 할당 드립니다!
제일 쉽게 해결하는 방법은 history.replaceState 이 부분을 window.location.href = 으로 변경하는 방법입니다
근데 그러면 nextjs 의 route.push 임에도 불구하고 새로고침처럼 전체가 렌더링 되기 때문에 해결이라고 볼 수는 없음..

**Comment by 2-NOW** [comment]
첫번째 요구사항의 방법 건의 (postMessage api 사용)
1. route 이동을 listen
  e.g. Link 컴포넌트를 한번 감싸거나, Link 컴포넌트 dom element의 event listen
2. 이동 시 postMessage api를 사용하여 iframe window에 메세지를 보낸다
3. iframe window에서는 메세지로 받는 route에 따라 내부의 route를 제어한다

**Comment by minsoo-web** [comment]
웨일! postMessage 로 되어있어요!
FYI https://github.com/hamsurang/origin/blob/main/packages/utils/src/iframeEventHandler.ts

**Comment by 2-NOW** [comment]
아하 ..!
자식에게도 똑같이 postMessage 하면될거같은데 뭔가 문제가 있나보네요 🤔

**Comment by minsoo-web** [comment]
> 아하 ..!
> 자식에게도 똑같이 postMessage 하면될거같은데 뭔가 문제가 있나보네요 🤔

아! 웨일 제가 잘못 이해했어요.
부모에서 자식에게 postMessage를 쏘고 있지 않은데 이건 생각 못해봤네요!! 지금은 단방향 소통이라 좋은 방법인 것 같아요!! 
작업하실 때 @sonsurim 확인 부탁해요!!

**Comment by sonsurim** [comment]
@minsoo-web  민수님 SSR 대응 관련해서 부모쪽에서는 가능할 것 같은데 자식쪽에서 가능할지 잘 모르겠네요..🧐
- **부모(web)** : 브라우저 api만 이용중 (addEventListener, history)
  -  [Script](https://nextjs.org/docs/pages/building-your-application/optimizing/scripts) 태그를 이용해서 이벤트 바인딩
- **자식(home, activity)** : next에 의존 (router)
