### ISSUE TITLE
[멤버] MbtiGraph 컴포넌트 구현

### ISSUE THREAD

**Issue by sonsurim** [hamsurang/origin#9]
- mbti 그래프를 표시합니다.

**Comment by minsoo-web** [comment]
@minchodang 민케이! 세부 요구사항을 업데이트해드릴려고 해요!

<img width="550" alt="image" src="https://github.com/hamsurang/origin/assets/57122180/bdbc95ee-256c-4e3b-bfa3-ed2d0d9a5fcd">

좌: MBTI에서 제공하는 png 를 활용한 멤버별 MBTI 표기
우: 작업 담당자가 생각하는 MBTI 퍼센트 (예시: 쿼카는 infp 에서 i 가 80%, n이 100%, f가 60%, p가 100% 인 것 같다)

추가로 궁금하신 게 있으면 코멘트 남겨주세요!

**Comment by minchodang** [comment]
@minsoo-web 
넵 일단 의문이 드는 점 코멘트 남겨 놓습니다. 
1. 좌측의 mbti png는 혹시 어디서 제공받으면 되는 건가요?(+ 저작권 상의 문제는 없는 지)
2.작업 담당자라 하면, 예를 들어 현재 컴포넌트를  작업하는 작업자(=저(@minchodang ))를 의미하는 것인지 아니면, 추후 각자 페이지에 대한 마크다운을 작업할 작업 담당자(클라이머 개개인)를 의미하는 것인지? 
3. 그러면 저 기준이 12시 시계 방향으로 시작해서 3시, 6시, 9시 기준으로 각각의 mbti 성향을 적어주면 되는 것인지? 

일단은 이렇게 총 3가지가 궁금합니다.
